# Generated by Django 2.2.6 on 2020-05-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_clearence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tectile',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Clasic',
        ),
        migrations.DeleteModel(
            name='Clearence',
        ),
        migrations.DeleteModel(
            name='Comfort',
        ),
        migrations.DeleteModel(
            name='Polo',
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
        migrations.DeleteModel(
            name='Sweatpant',
        ),
    ]
