# Generated by Django 2.2.6 on 2020-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200530_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=50)),
            ],
        ),
    ]
